name: Process spreadsheet
on:
  #schedule:
  #  - cron: '0 3 */4 * *'
  workflow_dispatch:

jobs:
  update-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Download and uplift files
        run: |
          cd ontology
          pip install rdflib openpyxl
          python scripts/species.py source.xlsx
          python scripts/vocabularies.py source.xlsx
          python scripts/properties.py source.xlsx
      - name: Commit new versions of files
        uses: EndBug/add-and-commit@v9
        with:
          add: ontology/output
          message: "Generated new version of ontology"
          default_author: github_actions

