name: Push to RAINBOW

on:
  workflow_dispatch:
    inputs:
      fileGlob:
        type: string
        description: Files to push (glob). Leave empty for everything.

jobs:
  uplift:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/opengeospatial/ogc-na-tools.git
      - name: Process files
        env:
          DB_USERNAME: ${{ secrets.UPLOAD_GRAPH_STORE_USERNAME }}
          DB_PASSWORD: ${{ secrets.UPLOAD_GRAPH_STORE_PASSWORD }}
        run: |
          if [ -n "${{ inputs.fileGlob }}" ]; then
            WHAT="-m ${{ inputs.fileGlob }}"
          else
            WHAT="--batch"
          fi
          python -m ogc.na.update_vocabs .ogc/catalog.ttl ${WHAT}  -w . \
           --update --graph-store https://defs-hosted.opengis.net/fuseki-hosted/data
